FROM search/zookeeper-docker
ARG nodeid=1
RUN\
	touch /zk-data/myid &&\
	echo ${nodeid} > /zk-data/myid  &&\
	echo "server.1=zoo1:2888:3888" >> /zk/conf/zoo.cfg &&\
	echo "server.2=zoo2:2888:3888" >> /zk/conf/zoo.cfg &&\
	echo "server.3=zoo3:2888:3888" >> /zk/conf/zoo.cfg &&\
	touch start.sh &&\
	echo "#!/usr/bin/env bash" >> start.sh &&\
	echo "./zk/bin/zkServer.sh start" >> start.sh &&\
	echo "tail -F /zookeeper.out" >> start.sh &&\
	chmod 755 start.sh
CMD	/bin/bash