FROM search/solrcloud-docker
RUN\
	touch start.sh &&\
	echo "#!/usr/bin/env bash" >> start.sh &&\
	echo "./solr/bin/solr stop" >> start.sh &&\
	echo "./solr/bin/solr -V -e techproducts -cloud -z zoo1:2181,zoo2:2181,zoo3:2181 -s /solr-data" >> start.sh &&\
#	echo "./solr/server/scripts/cloud-scripts/zkcli.sh -cmd upconfig -z localhost:2181 -confname data_driven -confdir ./solr/server/solr/configsets/data_driven_schema_configs/conf" >> start.sh &&\
	echo "tail -F /solr/server/logs/solr.log" >> start.sh &&\
	chmod 755 start.sh
CMD	/bin/bash
